// <auto-generated />
namespace Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CurrentRankingTopicId2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CurrentRankingTopicId2));
        
        string IMigrationMetadata.Id
        {
            get { return "201409151616432_CurrentRankingTopicId2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
